### ISSUE TITLE
Cannot upgrade

### ISSUE THREAD

**Issue by cybersiddhu** [gugod/App-perlbrew#226]
I cannot upgrade from 0.43

``` bash
$_> perlbrew --version
/Users/sid/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.43

$_> perlbrew self-upgrade
Unable to detect version of new perlbrew!
```

I am on Mac OSX 10.5.8

**Comment by hermidalc** [comment]
This issue shouldn't be reopened because it still exists in the latest version of perlbrew 0.74 and it's been the same issue in every previous version I've had installed.  The self-upgrade functionality doesn't work and while there is a workaround it should still be fixed or removed altogether.

On latest version 0.74 I still get:
```
$ perlbrew self-upgrade
Unable to detect version of new perlbrew!
```
