### ISSUE TITLE
Move default local::lib from ~/perl5 to ~/perl5/perlbrew/lib

### ISSUE THREAD

**Issue by saturdaywalkers** [gugod/App-perlbrew#468]
Am using perl on shared-hosting. Had a lot of trouble installing perlbrew.

The shared-hosting's cpanel (a web browser based config tool) installs libs in ~/perl5 using perl 5.8.8

So when I install 5.22, it didn't play nicely.

Could the default local::lib be (e.g.)
~/perl5/perlbrew/lib
~/perl5/perlbrew/perls/[version]/site-perl

(Or at least add the various environment variables to the documentation with some examples of how to change it yourself)

Thanks for all the work. Its appreciated.

**Comment by gugod** [comment]
Take a look at `perlbrew help lib`, I think that may provide some work-around for your condition. perlbrew itself has a special `local::lib` integration that should be usable orthogonaly with system perl. But it is basically munging a shared PERL5LIB env, you might run into some edge case that make it fail.

**Comment by Grinnz** [comment]
Note that in general, local::libs are not usable between different perl installations, primarily because of compiled XS code. So the modules in ~/perl5/lib are not going to be usable via your 5.22 perl anyway. This is why if you want to use local::lib with perlbrew, you need to use the embedded ones which are only for one perl installation.
