### ISSUE TITLE
Installation instructions should use https instead of http

### ISSUE THREAD

**Issue by timrs2998** [gugod/App-perlbrew#485]
https://github.com/gugod/App-perlbrew/blob/develop/README#L24 provides installation instructions open to MITM attacks and should use https. You could probably host the shell script in the GitHub repo instead of the http://perlbrew.pl/ website.

**Comment by lianyi** [comment]
+1

**Comment by gugod** [comment]
I pushed c4460eb6a6fb8f2db3c72948649a94a0277e1ca2 and 51aed31d605817c085848df2c070899b7232a322 to replace some http:// URLs in the documentation and code.

**Comment by gugod** [comment]
https://twitter.com/gugod/status/735942541858766849

I forgot to update this ticket... but since that tweet, all *.perlbrew.pl websites are all https ready. When being visited with http:// , the UA should be redirected to https://

Documentation were mostly updated to use https:// URLs. This issue can finally be closed.
