### ISSUE TITLE
Certificate issues with install.perlbrew.pl?

### ISSUE THREAD

**Issue by billmoseley** [gugod/App-perlbrew#519]
Recently (in the last month) I've been seeing certificate issues with install.perlbrew.pl.

Anyone else notice this?

```
$ curl -L https://install.perlbrew.pl
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
I'm seeing that on CentOS 6.5, CentOS 6.8 and Ubuntu 12.04.5 LTS.  Seems to work just fine on OS X 10.11.6.

**Comment by gugod** [comment]
Looks like the cert verification is currently failing for some reason, as indicated by this command:

    openssl s_client -showcerts -connect install.perlbrew.pl:443

    ....
    Verify return code: 21 (unable to verify the first certificate)

Not sure what has happened, need to dig into the process.... stay tuned.

**Comment by billmoseley** [comment]
For now I'm fetching directly from:
`https://raw.githubusercontent.com/gugod/App-perlbrew/master/perlbrew-install`

I suspect we have old ca cert files on our machines or something like that....   I'm curious if anything changed recently on the perlbrew site.

**Comment by gugod** [comment]
Thanks this info provided by gslin  https://www.ssllabs.com/ssltest/analyze.html?d=install.perlbrew.pl

**Comment by gslin** [comment]
Looks like intermediate certificate is not installed.

**Comment by moollaza** [comment]
FWIW I'm seeing the same issue as @billmoseley did before, but on OSX 10.12

Chrome also complains that the cert for perlbrew.pl is "invalid". Safari and Firefox have no problems with it though.

<img width="1183" alt="privacy_error_and_certificate_issues_with_install_perlbrew_pl__ _issue__519_ _gugod_app-perlbrew" src="https://cloud.githubusercontent.com/assets/873785/19154688/951f4aa2-8ba9-11e6-933c-28979f549291.png">

**Comment by gugod** [comment]
I've finally fix the mis-configured nginx. (I basically studied how various letsentrypt client worked, but turns out those are irrelevant to this issue...  :coffee: )

The "ssl_certificate" should be set to "fullchain.pm" instead of "cert.pm". The final config looks like:

    ssl_certificate /etc/.../fullchain.pem;

While previously it looks like

    ssl_certificate /etc/.../cert.pem;

cert.pem contains only the last certificate for the domain, while fullchain.pem contains cert.pem combined with other intermidate certificates. Matching what @gslin mentioned.

I did not recall how the config mutated int this broken state because it had been OK for months... I suspet that the automatic cert renewal did something unexpected, but I did not keep the log long enough for investigation. *sigh* that's fine.

I tested with "openssl", "curl", and firefox. All of them are able to verify SSL connection. So I'm closing this issue. Feel free to re-open it if necessary.

ref: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by Phylloxera** [comment]
Re-opening this ticket... apologize if inappropriate. I am using the /wget -O command to download perlbrew and the install goes just fine. My colleague on the same system, non-root on CentOS 6, issues the same command and gets:
curl: (77) error setting certificate verify locations:
  CAfile: /usr/share/ssl/certs/ca-bundle.crt
  CApath: none
Seems odd, a curl error following a wget command. Makes me think something in his user settings is awry. But, I can't think what. Prior to this, he was able to install perlbrew, but patchperl failed. He subsequently force removed the perl5 subfolder to retry. That's when the cert error started appearing.

**Comment by kalamnuri** [comment]
I am getting this same error for curl on Red Hat Enterprise Linux Server release 6.8 (Santiago)
wget is also throwing error "ERROR: cannot verify install.perlbrew.pl’s certificate" 
Is anyone else seeing this?
