### ISSUE TITLE
perlbrew list gives unwanted extra information

### ISSUE THREAD

**Issue by nigelhorne** [gugod/App-perlbrew#597]
How do I turn off the "installed on" that now appears on 'perlbrew list' output?  It makes it more difficult to slurp and parse in shell scripts.  Would be better to not have it, but if you want it use 'perlbrew list -l' or something like that.

**Comment by gugod** [comment]
cc @fluca1978

**Comment by gugod** [comment]
@nigelhorne Since you are pasing the output of commands... would it make better sense to have a notion of machine-readible output ? (like the `--porcelian` option for `git log`).

**Comment by fluca1978** [comment]
@gugod, you beated me on time: I believe we should have a kind of "stable" command output, like json or something else, for each command. That will allow us to mess the text form leaving the other one stable.

**Comment by nigelhorne** [comment]
I don't mind, to be honest.  Though I would prefer that the basic interface didn't change and when new features are added (such as the installation date and reversal of the sort order) that they be added as new options.

You could also add an option to output in some standard format such as CSV.

**Comment by fluca1978** [comment]
It is not only about new features and options, it could happen to slightly change the output format because, let's say, an '*' is changed to another symbol. That would break automated scripts the same way.
I believe there should be a way to get some parseable output, and that is what we should feed into scripts.
Of course, the important thing to understannd is how many consumers there are out there.
