### ISSUE TITLE
perlbrew switch not persisting on macOS Catalina

### ISSUE THREAD

**Issue by mjrodgers** [gugod/App-perlbrew#695]
I am using perlbrew version 0.88 on macOS Catalina 10.15.7, under the zsh shell.

I had my perlbrew all up and running in the past, but at some point recently (past 3-4 months I think?) it stopped working. I noticed that scripts were defaulting to run on the system perl instead of my perlbrew.

I am properly (I think) sourcing, I have this command as the very last line of my `.zshenv` file:
`source ~/perl5/perlbrew/etc/bashrc`

And it seems to be sourcing properly:
`(base) ➜  ~ type perlbrew`
`perlbrew is a shell function from /Users/mrodgers/perl5/perlbrew/etc/bashrc`

However:
`(base) ➜  ~ which perl`
`/usr/bin/perl`

I can switch 
`(base) ➜  ~ perlbrew switch perl-5.30.3`
`(base) ➜  ~ which perl`
`/Users/mrodgers/perl5/perlbrew/perls/perl-5.30.3/bin/perl`

but it reverts back to system perl every time when I open a new shell.

**Comment by gugod** [comment]
I believe this is due to the effect of a program called `path_helper`. At some point, macOS introduced the use of `/usr/libexec/path_helper` in the system-wide  `/etc/zprofile` as, I guess, a way to mantain a canonical  order of items in `$PATH`. 

The issue with `path_helper` and perlbrew is that, `path_helper` reorder the items in `$PATH` and  system-y paths are moved to the beginning. While perlbrew needs a few paths to be in the beginning of `$PATH` in order to make the switching logic work.

iirc you need to put the statement `source ~/perl5/perlbrew/etc/bashrc` in the end of `~/.zprofile` -- this should be able to let the perlbrew bashrc do its thing after `path_helper`

**Comment by mjrodgers** [comment]
Thank you!!! Moving this line from the end of `.zshrc` to the end of `.zprofile` fixed the problem. Thanks 100x more for my latexindent working properly again.
